enum RETURN_TYPES {
  SUCCESS,
  INVALID_CREDENTIALS,
  USER_NOT_FOUND,
  EMAIL_IN_USE,
  WEAK_PASSWORD,
  REGISTRATION_FAILED,
  CREDENTIALS_REQUIRED,
  GOOGLE_LOGIN_FAILED,
  PASSWORDS_NOT_MATCH,
  LOGIN_FAILED,
}

export default RETURN_TYPES;
