"""Modified user model

Revision ID: 1579eaa9929f
Revises: 289a80d00621
Create Date: 2025-03-20 00:12:53.701911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1579eaa9929f'
down_revision = '289a80d00621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_uid', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('user_google_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['google_uid'])
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_google_id_key', ['google_id'])
        batch_op.drop_column('google_uid')

    # ### end Alembic commands ###
